docs_dir: docs
site_name: search-test
repo_url: https://github.com/halx99/search-test
repo_name: GitHub
edit_uri: edit/master/docs
copyright: Copyright &copy; 2012 - 2021 search-test.org.
theme:
  name: material
  language: zh
nav:
  - Home: index.md
plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\，\。]+'
